### ISSUE TITLE
The payment request on Wordline does not correspond to the shopping cart on PrestaShop

### ISSUE THREAD

**Issue by d33x** [wl-online-payments-direct/plugin-prestashop#4]
Since the beginning of February, we have had several customers report that the amount in their basket does not correspond to the amount that Wordline is asking them to pay. It seems that you are trimming the first figure each time.

If the customer is asked to pay €138.90, Wordline asks them to pay €38.90.
![payment-error](https://github.com/wl-online-payments-direct/plugin-prestashop/assets/76649472/aeeb19c5-6122-4457-ade3-a51740a3679b)
![payment-error-2](https://github.com/wl-online-payments-direct/plugin-prestashop/assets/76649472/864d7ad0-64bd-4ab1-9641-098379ccbc2f)

We have several cases like this @WorldlineShoppingCarts

**Comment by PrestaEdit** [comment]
FIY, I wrote the same issue on the Marketplace support.

Once you change the delivery method, the transaction is not updated and the price remain the same.

Look forward to get an answer on this.

**Comment by d33x** [comment]
Thank you for your message. I didn't notice this problem appearing with a change of delivery method. I'm having a meeting today with their support team to try and find out more about the problem.

From what I've noticed, on my side, the problem appeared at the beginning of February (without any change on our side). The first digit is truncated every time when the redirection to the payment is not done correctly:
- Amount error when the customer is not redirected to the Wordline payment page after the "Order" button and stays on our PrestaShop directly "XXX/fr/commande" to make the payment
- No error when the customer is redirected to "payment.direct.ingenico.com/" after " Order ".

**Comment by PrestaEdit** [comment]
Solved ?

**Comment by d33x** [comment]
My case is solved, but the case of the delivery method, which doesn't change, is not. But the two cases are not linked.
